# action.yml
name: "nba download action"
description: "downloads game data from the NBA and stores to filesystem"
author: "stephenhu"
inputs:
  source:
    description: "source file path"
    required: true
    default: "."
runs:
  using: "docker"
  image: "docker://ghcr.io/stephenhu/nbac:v1"
brand:
  icon: "layers"
  color: "blue"
